server:
  port: 2010
  error:
    include-message: always

spring:
  gateway:
    routes:
      - id: spring_demo
        uri: http://localhost:8080/api/demo
        predicates:
          - Path=/api/demo
          - Method=GET
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/TravelMarketPlace
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true